version: '3.8'
services:
  bloomdb:
    container_name: bloomrunnerDb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pwd12345!"
    ports:
      - '1422:1433'
    restart: on-failure

  webgateway.api:
    container_name: webapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4001:443"
      - "4000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  authservice.api:
    container_name: authservice
    restart: on-failure
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Data Source=bloomrunnerdb;Initial Catalog=BloomRunner;User id=sa;Password=Pwd12345!;Trusted_Connection=false;Integrated Security=false
    depends_on:
        - bloomdb
    ports:
        - "5001:443"
        - "5000:80"

  category.api:
    container_name: category.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    volumes:
        - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
        - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
        - "6001:443"
        - "6000:80"

  florist.api:
    container_name: florist
    depends_on:
        - bloomdb
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    volumes:
        - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
        - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
        - "7001:443"
        - "7000:80"